### GET all
GET http://localhost:8080/api/todos

### CREATE todo
POST http://localhost:8080/api/todos
Content-Type: application/json

{
  "title": "My first todo",
  "completed": false
}

### GET by id
GET http://localhost:8080/api/todos/  v c

### UPDATE
PUT http://localhost:8080/api/todos/1
Content-Type: application/json

{
  "title": "Updated todo",
  "completed": true
}

### DELETE
DELETE http://localhost:8080/api/todos/1